name: Generate or update list of tracked links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  push:
    # trigger on updated link crawler rules
    branches:
      - main

jobs:
  make_tracked_links_file:
    name: Make tracked links file
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:

      - name: Clone.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python.
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt

      - name: Generate/update file with links.
        env:
          OUTPUT_FILENAME: "tracked_links_ci.txt"
          OUTPUT_RESOURCES_FILENAME: "tracked_res_links_ci.txt"
        run: |
          python make_tracked_links_list.py

      - name: Commit and push changes.
        run: |
          git pull

          mv tracked_links_ci.txt tracked_links.txt
          mv tracked_res_links_ci.txt tracked_res_links.txt

          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

          git add .
          git commit -m "Update tracked links"
          git push
